#!/usr/bin/env python3
"""Render the STOCK -> TUNE #24 delta as a human-readable report.

Reads data/2010_silverado_delta_stock_to_24.json (produced by
tools/delta_stock_to_24.py) and writes docs/TUNE-24-DELTA.md.

The report answers one question: what did tune #24 actually change?
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ENCODING = "utf-8"
ROOT = Path(__file__).resolve().parent.parent
DELTA_FILE = ROOT / "data" / "2010_silverado_delta_stock_to_24.json"
REPORT_FILE = ROOT / "docs" / "TUNE-24-DELTA.md"

# What each change actually does to the truck. Keyed by (module, param_id).
# These are engineering consequences of the numbers in the delta, not extra
# data: nothing here alters a value or a classification.
DRIVABILITY: dict[tuple[str, int], str] = {
    ("ECM", 9050): "ECM speed/distance maths. Wrong here skews the speedometer, "
                   "odometer and every speed-gated ECM function.",
    ("ECM", 9052): "The VSS-error companion to 9050. Must track it or the ECM's "
                   "own plausibility check misfires.",
    ("TCM", 5004): "TCM gear-ratio maths. Wrong here skews shift scheduling, TCC "
                   "apply and ratio-based diagnostics (P0730 family).",
    ("ECM", 9054): "Driven-wheel rolling circumference. Sets indicated speed and "
                   "distance together with the axle ratio.",
    ("ECM", 9056): "Non-driven circumference. Same tyres on all four corners, so "
                   "it must equal 9054 or wheel-speed comparison logic drifts.",
    ("TCM", 15010): "The daily-driving WOT upshift schedule. This is the one that "
                    "decides whether a full-throttle 1-2 lands near peak power or "
                    "past the limiter on 4.11s and 35s.",
    ("TCM", 15012): "Hot-transmission WOT schedule. Governs full-throttle shifts "
                    "once trans temp is up - the towing case.",
    ("TCM", 15015): "Tow/Haul WOT schedule.",
    ("TCM", 15017): "Hot-engine WOT schedule.",
    ("TCM", 15323): "Performance/tip-in WOT pattern A.",
    ("TCM", 15326): "Alternate performance WOT pattern B.",
}

LOAD_BEARING = set(DRIVABILITY)


def fmt(value: Any) -> str:
    if isinstance(value, float):
        if value == int(value):
            return str(int(value))
        return f"{value:g}"
    return str(value)


def render(delta: dict[str, Any]) -> str:
    meta = delta["metadata"]
    params = delta["parameters"]
    changed = [e for e in params if e["status"] == "changed"]
    by_key = {(e["module"], e["param_id"], e["kind"]): e for e in params}

    out: list[str] = []
    add = out.append

    add("# What tune #24 actually changed")
    add("")
    add(f"**{meta['vehicle']}** — VIN {meta['vin']}")
    add("")
    add(f"Stock baseline: `{meta['stock_source']['base_tune']}` "
        f"(sha256 `{meta['stock_source']['base_tune_sha256'][:16]}…`)  ")
    add(f"Tune: `{meta['tune24_sources']['swept']['base_tune']}`")
    add("")
    add("> Generated by `tools/delta_report.py` from "
        "`data/2010_silverado_delta_stock_to_24.json`. Do not hand-edit.")
    add("")

    # ---- headline ------------------------------------------------------
    add("## The answer")
    add("")
    add(f"**Tune #24 changed {len(changed)} parameters.** Every one of them is "
        "load-bearing for drivability; there are no incidental edits.")
    add("")
    add("1. **The axle ratio, in all three places it is stored** — 3.08 → 4.11.")
    add("2. **Tyre rolling circumference, both axles** — 2475 → 2742 mm.")
    add("3. **All six WOT shift-speed schedules in the TCM** — mostly rescaled "
        "to ≈0.83× stock, with one deliberate exception noted below.")
    add("")
    add("Those three groups are one coherent edit: the truck physically got "
        "4.11 gears and 35\" tyres, #24 told both controllers so, and then "
        "pulled the full-throttle shift speeds down so the engine still shifts "
        "near peak power instead of running into the limiter on the taller "
        "tyres and shorter gears.")
    add("")
    add("The exception is worth seeing, because it is the signature of a "
        "deliberate hand edit rather than a blanket rescale: on `TCM:15010`, "
        "the everyday Normal schedule, the **1-2 upshift was raised** 33 → 35 "
        "mph (+6.1%) and the 2-1 downshift 30 → 31 mph, while 2-3 and above "
        "were pulled down 12–16%. Every other table was scaled down uniformly. "
        "Someone chose to hold first gear slightly longer from a standstill on "
        "the daily schedule and only then start shortening the rest.")
    add("")
    add("**#24 did not touch anything else that both sides cover.** All 369 "
        "scalars and 240 of the 246 comparable tables the #24 sweep holds are "
        "identical to stock.")
    add("")

    # ---- AFM -----------------------------------------------------------
    afm = by_key.get(("ECM", 246, "scalar"))
    if afm:
        add("### AFM/DoD: #24 did *not* disable it")
        add("")
        add(f"`ECM:246 {afm['stock_name']}` reads **{fmt(afm['stock_value'])} "
            f"(\"{afm['stock_raw']}\")** in the genuine October-2024 pre-tuning "
            "read. AFM was **already disabled before #24 existed**.")
        add("")
        add("The tune is named \"4.11 Gears, DOD Delete, Shift Points\", so the "
            "DOD-delete half of that name describes a state #24 inherited, not "
            "a change it made. Any delta that reports #24 disabling AFM is "
            "wrong, and this is the check that catches it.")
        add("")

    # ---- the changes ---------------------------------------------------
    add("## The changes, in order of how much they matter")
    add("")
    add("| # | Module | ID | Parameter | Stock | #24 | Unit | Why it matters |")
    add("|---|--------|----|-----------|-------|-----|------|----------------|")
    for i, e in enumerate(changed, 1):
        key = (e["module"], e["param_id"])
        why = DRIVABILITY.get(key, "—")
        if e["kind"] == "scalar":
            stock_s, tune_s = fmt(e["stock_value"]), fmt(e["tune24_value"])
        else:
            stock_s = f"{e['cells_changed']} cells"
            tune_s = f"×{e['min_ratio']:.3f}–{e['max_ratio']:.3f}"
        add(f"| {i} | {e['module']} | {e['param_id']} | {e['name']} | "
            f"{stock_s} | {tune_s} | {e['unit'] or '—'} | {why} |")
    add("")

    # ---- shift tables cell detail --------------------------------------
    add("## WOT shift schedules, cell by cell")
    add("")
    add("Every WOT table is stored per gear-change event. VCM Editor exposes "
        "six of them (three upshifts, three downshifts); the four remaining "
        "events are covered separately below.")
    add("")
    for e in [c for c in changed if c["kind"] == "table"]:
        add(f"### TCM:{e['param_id']} — {e['name']}")
        add("")
        add(f"Source: `{e['primary_source']}`, aligned {e['alignment']}. "
            f"Cross-check against the independent stock sweep: "
            f"{e['sheet24_stock_claim_check']['cells_agreeing']}/"
            f"{e['sheet24_stock_claim_check']['cells_checked']} cells agree.")
        add("")
        add("| Shift | Stock (mph) | #24 (mph) | Change | Ratio |")
        add("|-------|------------:|----------:|-------:|------:|")
        for cell in e["changed_cells"]:
            label = cell.get("label") or f"row {cell['row']}"
            ratio = cell["tune24"] / cell["stock"] if cell["stock"] else float("nan")
            add(f"| {label} | {fmt(cell['stock'])} | "
                f"{fmt(round(cell['tune24'], 1))} | {cell['pct']:+.1f}% | "
                f"×{ratio:.3f} |")
        add("")
        extra = e.get("sheet24_only_cells") or []
        if extra:
            add(f"Four further gear events ({', '.join(c['label'] for c in extra)}) "
                "appear on the hand-entered tune sheet but VCM Editor never "
                "exposed those rows, so **there is no stock sweep reading to "
                "confirm them**. They are recorded but not counted as confirmed "
                "changes:")
            add("")
            add("| Shift | Sheet's stock claim | Sheet's #24 value | Status |")
            add("|-------|--------------------:|------------------:|--------|")
            for cell in extra:
                add(f"| {cell['label']} | {fmt(cell['sheet24_stock_claim'])} | "
                    f"{fmt(cell['sheet24_tune_value'])} | unconfirmed, "
                    "single-source |")
            add("")

    # ---- how it was derived --------------------------------------------
    add("## How this was derived, and what would have made it wrong")
    add("")
    add("### Join key")
    add("")
    add(f"`{meta['join_key']}`. Three traps make a name match produce false "
        "results:")
    add("")
    add("- `Final Drive Ratio` exists as **both** `ECM:9050` and `TCM:5004`. A "
        "name match collapses two distinct parameters into one.")
    add("- The tune sheet calls `ECM:246` *\"DoD (AFM) Enable\"*; VCM Editor "
        "calls it *\"DoD Enable\"*. An exact-name match scores it **MISSING**.")
    add("- Neither #24 file carries a `module` field at all, so the module had "
        "to be derived before the key could even be formed.")
    add("")
    add("Module derivation: stock's `param_id → module` map has **zero "
        "cross-module collisions**, and the #24 table file embeds an "
        "`[ECM] id N` tag in its notes. The two agree on **245/245** "
        "overlapping tables with zero conflicts, so the derivation is "
        "corroborated rather than assumed.")
    add("")

    add("### The rounding trap that nearly produced 11 false changes")
    add("")
    add("The stock sweep stores values as VCM Editor *displayed* them; the #24 "
        "sweep stores full float precision off the calibration:")
    add("")
    add("| Stock displays | #24 holds | Float delta | Truth |")
    add("|----------------|-----------|-------------|-------|")
    add("| `6,042` | 6041.924736342039 | −0.075 | same value |")
    add("| `19.9688` | 19.96875 | −0.00005 | same value |")
    add("| `16.2` | 16.25 | +0.05 | same value |")
    add("| `33` | 35.000674187743584 | +2.0 | **real change** |")
    add("")
    add("A half-ULP float tolerance called 16 tables changed; 11 of those were "
        "pure display rounding. Equality is instead decided by rounding the #24 "
        "value to stock's displayed precision, **half-to-even** — confirmed "
        "against 15 independent cells including `1.84375 → \"1.8438\"` and "
        "`1.53125 → \"1.5312\"`, which only half-to-even reproduces. "
        "This suppresses 11,523 artefact cells across 137 tables.")
    add("")
    add("A second bug fed the same failure: VCM Editor writes thousands "
        "separators, so `\"6,042\"` failed the numeric parse and four tables "
        "fell back to a table-wide precision far tighter than the display.")
    add("")

    add("### Coverage — surplus, not loss")
    add("")
    stock_src = meta["stock_source"]
    swept_src = meta["tune24_sources"]["swept"]
    add(f"The stock sweep captured **{stock_src['scalars']} scalars / "
        f"{stock_src['tables']} tables**; the #24 sweep holds "
        f"**{swept_src['scalars']} / {swept_src['tables']}**. VCM Editor in "
        "Advanced view across ECM+TCM exposes more than the older coalesced "
        "#24 file ever contained. **That surplus is extra stock coverage, not "
        "missing #24 data.**")
    add("")
    add("Critically, the axle, tyre and AFM parameters are **absent from the "
        "swept #24 file entirely** — `data/2010_silverado_24.cal.json`, the "
        "hand-entered tune sheet, is their only source. Its stock claims are "
        "checkable against the independent sweep on 36 WOT cells and agree on "
        "**36/36**, which is what makes it trustworthy enough to carry the "
        "five axle/tyre changes.")
    add("")
    add("| Classification | Count | Meaning |")
    add("|----------------|------:|---------|")
    labels = {
        "changed": "#24 changed it",
        "unchanged": "#24 left it identical to stock",
        "stock_only_tune24_unmeasured":
            "read in stock, **no #24 reading at all** — UNKNOWN, not unchanged",
        "tune24_only_stock_unmeasured":
            "read in #24, not captured by the stock sweep — stock side UNKNOWN",
    }
    for status, count in delta["summary"]["by_status"].items():
        add(f"| `{status}` | {count} | {labels.get(status, '')} |")
    add("")
    add("The 690 unmeasured parameters are **not** evidence that #24 left them "
        "alone. They are parameters no #24 reading covers. Missing is recorded "
        "as missing.")
    add("")

    add("### `2010_silverado_best.cal.json` is obsolete — do not use it")
    add("")
    add(meta["excluded_source"]["reason"])
    add("")
    add("It existed as a workaround for having no stock baseline. The baseline "
        "now exists, so the workaround should be retired rather than "
        "maintained.")
    add("")

    # ---- self check ----------------------------------------------------
    add("## Six-pin self-check")
    add("")
    add("The six hand-verified pins are the known-true anchor for the whole "
        "derivation. Five must fall out as changes and AFM must fall out as "
        "**not** a change.")
    add("")
    add("| Pin | Expected | Delta says | Result |")
    add("|-----|----------|------------|--------|")
    pins = [
        ("ECM", 9050, "scalar", "3.08 → 4.11", True),
        ("ECM", 9052, "scalar", "3.08 → 4.11", True),
        ("TCM", 5004, "scalar", "3.08 → 4.11", True),
        ("ECM", 9054, "scalar", "2475 → 2742 mm", True),
        ("ECM", 9056, "scalar", "2475 → 2742 mm", True),
        ("ECM", 246, "scalar", "unchanged (already disabled in stock)", False),
    ]
    passed = 0
    for module, pid, kind, expected, should_change in pins:
        entry = by_key.get((module, pid, kind))
        if entry is None:
            add(f"| `{module}:{pid}` | {expected} | **absent** | FAIL |")
            continue
        actual = (f"{fmt(entry['stock_value'])} → {fmt(entry['tune24_value'])}"
                  if should_change else f"{entry['status']}")
        ok = (entry["status"] == "changed") == should_change
        passed += ok
        add(f"| `{module}:{pid}` {entry['name']} | {expected} | {actual} | "
            f"{'PASS' if ok else 'FAIL'} |")
    add("")
    add(f"**{passed}/6 pins reconcile.** Enforced by "
        "`tests/test_delta_stock_to_24.py`, which fails the build if the "
        "headline change count moves or a pin stops reconciling.")
    add("")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--delta", type=Path, default=DELTA_FILE)
    parser.add_argument("--out", type=Path, default=REPORT_FILE)
    args = parser.parse_args()

    delta = json.loads(args.delta.read_text(encoding=ENCODING))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(delta), encoding=ENCODING)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
